name: test-branch

on:
  push:
    branches-ignore:
      - 'deploy'
      - 'emsdk/**'
    paths-ignore:
      - '**.md'
      - '**LICENSE'
      - '**.gitignore'

jobs:
  tests:
    strategy:
      matrix:
        os: [macos-latest,windows-latest,ubuntu-latest]
        node-version: [15.x, 14.x, 12.x]
    
    runs-on: ${{ matrix.os }}
    
    steps:
    - uses: actions/checkout@v2

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}

    - run: npm install
    - run: npm test
